---
title: "Análise de Gastos de Deputados: Suas Perguntas"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)

dadosCEAP <- read_csv("data/dadosCEAP.csv")
#View(dadosCEAP)

```


1) Com que tipo de despesa os deputados da paraiba mais gastam? Creio que deve ser com passagens aereas .
```{r}
despesasMaisFeitas = dadosCEAP %>%
  select(tipoDespesa,sgUF,valorLíquido)%>%
  filter (sgUF=='PB') %>%
  group_by(tipoDespesa)%>%
  summarise(gastosTotal = sum(valorLíquido))

despesasMaisFeitas = despesasMaisFeitas%>% top_n(5)

#View(despesasMaisFeitas)

despesasMaisFeitas %>%
  ggplot(aes(y=gastosTotal,x=tipoDespesa))+
  geom_bar(stat='identity')+
  labs(title="Tipos de despesas que Deputados da PB mais gastam",y="Valor",x="Estado do Deputado")+
  
  coord_flip()

```

2)
Quais são os tipos de despesas que os deputados da paraiba mais fazem? Acho que devem ser gastos com passagens aereas tambem:

```{r}
despesasMaisFeitas = dadosCEAP %>%
  select(tipoDespesa,sgUF,valorLíquido)%>%
  filter (sgUF=='PB') %>%
  group_by(tipoDespesa)
  

#despesasMaisFeitas = despesasMaisFeitas%>% top_n(5)

#View(despesasMaisFeitas)

despesasMaisFeitas %>%
  ggplot(aes(x=tipoDespesa))+
  geom_bar()+
  labs(title="Tipos de despesas que Deputados da PB mais fazem",y="Valor",x="Estado do Deputado")+
  
  coord_flip()
```

